volumes:
  postgres_data:
  redis-data:

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  db:
    container_name: db
    image: postgres:16.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_URI: jdbc:postgresql://db:5432/$POSTGRES_DB
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      CACHE_HOST: redis
      CACHE_PORT: 6379
      ENCRYPTION_SECRET: $ENCRYPTION_SECRET
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - backend
